import './globals.css';
import { Source_Sans_3 } from 'next/font/google';

const source = Source_Sans_3({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={source.className}>
        {' '}
        {children}
        <div id="modalPortal"></div>
      </body>
    </html>
  );
}
