'use client';
import './globals.css';
import { Source_Sans_3 } from 'next/font/google';
import { useIsModalOpen } from '@/lib/store';

const source = Source_Sans_3({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isModalOpen = useIsModalOpen();
  // console.log(isModalOpen);
  return (
    <html lang="en">
      <body
        className={`${source.className} ${
          isModalOpen ? 'overflow-hidden ' : ''
        } `}
      >
        {' '}
        <div className={` ${isModalOpen ? 'blur-[2px] ' : ''} `}>
          {children}
        </div>
        <div id="modalPortal"></div>
      </body>
    </html>
  );
}
